version: "3.8"

services:
  web:
    build: .
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ".:/usr/src/app"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_DEV}
      - POSTGRES_DB_TEST=${DB_NAME_TEST}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./create_second_db.sh:/docker-entrypoint-initdb.d/create_second_db.sh

volumes:
  postgres-db:
