// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	model "go-issues-api/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// IssueUsecase is an autogenerated mock type for the IssueUsecase type
type IssueUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: userId, title, description
func (_m *IssueUsecase) Create(userId int, title string, description string) (*model.Issue, error) {
	ret := _m.Called(userId, title, description)

	var r0 *model.Issue
	if rf, ok := ret.Get(0).(func(int, string, string) *model.Issue); ok {
		r0 = rf(userId, title, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Issue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = rf(userId, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBy provides a mock function with given fields: id
func (_m *IssueUsecase) DeleteBy(id int) (int64, error) {
	ret := _m.Called(id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(int) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *IssueUsecase) FindAll() ([]*model.Issue, error) {
	ret := _m.Called()

	var r0 []*model.Issue
	if rf, ok := ret.Get(0).(func() []*model.Issue); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Issue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAndUpdate provides a mock function with given fields: id, title, description
func (_m *IssueUsecase) FindAndUpdate(id int, title string, description string) (*model.Issue, error) {
	ret := _m.Called(id, title, description)

	var r0 *model.Issue
	if rf, ok := ret.Get(0).(func(int, string, string) *model.Issue); ok {
		r0 = rf(id, title, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Issue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = rf(id, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBy provides a mock function with given fields: id
func (_m *IssueUsecase) FindBy(id int) (*model.Issue, error) {
	ret := _m.Called(id)

	var r0 *model.Issue
	if rf, ok := ret.Get(0).(func(int) *model.Issue); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Issue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Vote provides a mock function with given fields: id, userId, vote
func (_m *IssueUsecase) Vote(id int, userId int, vote int) (*model.VoteIssue, error) {
	ret := _m.Called(id, userId, vote)

	var r0 *model.VoteIssue
	if rf, ok := ret.Get(0).(func(int, int, int) *model.VoteIssue); ok {
		r0 = rf(id, userId, vote)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.VoteIssue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(id, userId, vote)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIssueUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewIssueUsecase creates a new instance of IssueUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIssueUsecase(t mockConstructorTestingTNewIssueUsecase) *IssueUsecase {
	mock := &IssueUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
